#AI Intern Assignment 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = np.random.randn(4, 4)
df = pd.DataFrame(data, columns=['F1', 'F2', 'F3', 'F4'])

df

         F1        F2        F3        F4
0 -0.983580 -0.634964  3.919381 -0.743302
1  1.480452  0.510629  0.231514 -0.200675
2  0.446870  0.117702 -0.260664  0.689283
3  0.963853 -1.264807 -0.511315  0.507328

In [ ]:
new_column_names = {
    'F1': 'Random value 1',
    'F2': 'Random value 2',
    'F3': 'Random value 3',
    'F4': 'Random value 4'
}
df = df.rename(columns=new_column_names)

In [ ]:
df

   Random value 1  Random value 2  Random value 3  Random value 4
0       -0.983580       -0.634964        3.919381       -0.743302
1        1.480452        0.510629        0.231514       -0.200675
2        0.446870        0.117702       -0.260664        0.689283
3        0.963853       -1.264807       -0.511315        0.507328

In [ ]:
stats = df.describe()

In [ ]:
stats

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.476899       -0.317860        0.844729        0.063158
std          1.061154        0.790226        2.072862        0.660632
min         -0.983580       -1.264807       -0.511315       -0.743302
25%          0.089257       -0.792425       -0.323327       -0.336332
50%          0.705362       -0.258631       -0.014575        0.153326
75%          1.093003        0.215934        1.153481        0.552816
max          1.480452        0.510629        3.919381        0.689283

In [ ]:
df.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [ ]:
df.dtypes

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
df.loc[:, ['Random value 2', 'Random value 3']]

   Random value 2  Random value 3
0       -0.634964        3.919381
1        0.510629        0.231514
2        0.117702       -0.260664
3       -1.264807       -0.511315

In [ ]:
df.iloc[:, [1, 2]]

   Random value 2  Random value 3
0       -0.634964        3.919381
1        0.510629        0.231514
2        0.117702       -0.260664
3       -1.264807       -0.511315